FROM centos:7
MAINTAINER tjinjin

# setup
RUN yum update -y
RUN yum install -y rpm-build tar

# ruby depends
RUN yum -y install readline-devel ncurses-devel gdbm-devel glibc-devel gcc openssl-devel libyaml-devel libffi-devel zlib-devel

# build
WORKDIR /var/tmp/rpmbuild
ADD rubybuild.sh /var/tmp/rpmbuild/rubybuild.sh
ADD ruby22x.spec /var/tmp/rpmbuild/SPECS/ruby22x.spec
