FROM centos:7
MAINTAINER tjinjin

# setup
RUN yum update -y
RUN yum install -y rpm-build tar make

# ruby depends
RUN yum -y install readline-devel ncurses-devel gdbm-devel glibc-devel gcc openssl-devel libyaml-devel libffi-devel zlib-devel

RUN useradd docker

# build
RUN mkdir -p /var/tmp/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
RUN chown -R docker /var/tmp/rpmbuild
WORKDIR /var/tmp/rpmbuild
ADD rubybuild.sh /var/tmp/rpmbuild/rubybuild.sh
ADD ruby22x.spec /var/tmp/rpmbuild/SPECS/ruby22x.spec
ADD ruby-version /var/tmp/rpmbuild/ruby-version
